
project_id = "fkkzklaigpjtwldsctvj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
secure_channels = true

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"
s3_credentials_access_key_id = "625729a08b95bf1b7ff351a663f3a23c"
s3_credentials_secret_access_key = "850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aed6ded925671e6ed8"
s3_credentials_region = "local"

[auth]
enabled = true
port = 54324
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.openai-chat]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.web-search]
verify_jwt = true

[edge-runtime]
policy = "per_worker"
inspector_port = 8083

[analytics]
enabled = false
port = 54327
vector_port = 54328
gw_port = 54329
gw_api_port = 54330

[experimental]
orioledb_version = ""
s3_host = "127.0.0.1"
s3_port = 54329
s3_access_key_id = "625729a08b95bf1b7ff351a663f3a23c"
s3_secret_access_key = "850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aed6ded925671e6ed8"
s3_region = "local"
