// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkkzklaigpjtwldsctvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZra3prbGFpZ3BqdHdsZHNjdHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODY4NzcsImV4cCI6MjA2NTY2Mjg3N30.Elvc6ZI8BAH2CvIKw8rh8g9Y61Wz2XvkgfEjK74DmXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);